nome = str(input('Digite seu nome ')).strip()
print('Nome em maiúsculo '.format(nome.upper()))
print('Nome em minúsculo '.format(nome.lower()))
print('Seu nome ao todo tem '.format(len(nome) - nome.count(' ')))
#print('Seu primeiro nome tem '.format(nome.find(' ')))
sepera = nome.split()
print('Seu primeiro nome tem'.format(len(sepera[0])))