nome = str(input('Digite seu nome ')).strip()
print('Seu nome em maiúsculo: {}'.format(nome.upper()))
print('Seu nome em minúsculo: {}'.format(nome.lower()))
print('Seu nome tem {} letras' .format(len(nome)-nome.count(' ')))
primeiroNome = nome.split()
print('Seu primeiro nome tem: {}'.format(len(primeiroNome[0])))