nome = str(input('Digite um nome ')).strip()
print('O nome em maiúsculo: {}'.format(nome.upper()))
print('O nome em minúsculo: {}'.format(nome.lower()))
print('O nome sem espaço: {}'.format(len(nome) - nome.count(' ')))
pNome = nome.split()
print('O seu primeiro nome tem {} letras'.format(len(pNome[0])) )
